# Generated by Django 3.1.2 on 2020-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklending',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='librarycard',
            name='deactive_date',
            field=models.DateField(null=True),
        ),
    ]
