# Generated by Django 3.1.2 on 2020-10-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0002_auto_20201011_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='locatin_identifier',
            new_name='location_identifier',
        ),
    ]
