# Generated by Django 3.1.2 on 2020-10-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0003_auto_20201012_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='book',
            name='entry_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày nhập'),
        ),
        migrations.AlterField(
            model_name='book',
            name='location_identifier',
            field=models.CharField(max_length=255, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(verbose_name='Số trang'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.IntegerField(verbose_name='Năm xuất bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=255, verbose_name='Nhà xuất bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.CharField(max_length=7, verbose_name='Kích thước'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
