# Generated by Django 3.1.2 on 2020-10-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0004_auto_20201012_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklending',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Họ và Tên'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resgister_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tel_number',
            field=models.CharField(max_length=11, verbose_name='Số điện thoại'),
        ),
    ]
