# Generated by Django 3.1.2 on 2020-10-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0005_auto_20201012_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Trạng thái xử lý'),
        ),
        migrations.AlterField(
            model_name='booklending',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmagapp.book', verbose_name='Mã sách được mượn'),
        ),
        migrations.AlterField(
            model_name='booklending',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày mượn'),
        ),
        migrations.AlterField(
            model_name='booklending',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmagapp.member', verbose_name='Mã thành viên mượn'),
        ),
        migrations.AlterField(
            model_name='booklending',
            name='return_date',
            field=models.DateField(null=True, verbose_name='Ngày trả'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmagapp.member', verbose_name='Mã thành viên yêu cầu'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='requested_book_author',
            field=models.CharField(max_length=255, verbose_name='Tác giả sách yêu cầu'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='requested_book_title',
            field=models.CharField(max_length=255, verbose_name='Tên sách yêu cầu'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='requested_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày yêu cầu'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='date_of_birth',
            field=models.DateField(verbose_name='Ngày sinh nhân viên'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên nhân viên'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='tel_number',
            field=models.CharField(max_length=11, verbose_name='Số điện thoại nhân viên'),
        ),
        migrations.AlterField(
            model_name='librarycard',
            name='active_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày kích hoạt'),
        ),
        migrations.AlterField(
            model_name='librarycard',
            name='deactive_date',
            field=models.DateField(null=True, verbose_name='Ngày vô hiệu hóa'),
        ),
        migrations.AlterField(
            model_name='librarycard',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmagapp.member', verbose_name='Mã thành viên sở hữu'),
        ),
    ]
