# Generated by Django 3.1.2 on 2020-10-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0006_auto_20201013_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='tel_number',
            field=models.CharField(max_length=255, verbose_name='Số điện thoại nhân viên'),
        ),
        migrations.AlterField(
            model_name='librarycard',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmagapp.member', verbose_name='Mã thành viên'),
        ),
    ]
