# Generated by Django 3.1.2 on 2020-10-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0007_auto_20201013_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tel_number',
            field=models.CharField(max_length=255, verbose_name='Số điện thoại'),
        ),
    ]
