# Generated by Django 3.1.2 on 2020-10-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0012_remove_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
