# Generated by Django 3.1.2 on 2020-10-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0013_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number_of_pages',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pub_date',
            new_name='pubdate',
        ),
    ]
