# Generated by Django 3.1.2 on 2020-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0014_auto_20201014_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(default=None, max_length=255, verbose_name='Email'),
        ),
    ]
