# Generated by Django 3.1.2 on 2021-01-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0015_auto_20201014_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubdate',
            new_name='pub_year',
        ),
    ]
