# Generated by Django 3.1.2 on 2020-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0015_auto_20201014_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='Địa chỉ email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tel_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
