# Generated by Django 3.1.2 on 2020-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0016_auto_20201101_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='location_identifier',
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.IntegerField(choices=[(0, 'Generalities'), (1, 'Philosophy & psychology'), (2, 'Religion'), (3, 'Social sciences'), (4, 'Languages'), (5, 'Natural sciences & mathematics'), (6, 'Technology'), (7, 'The arts'), (8, 'Literature & rhetoric'), (9, ' Geography & history')], default=None),
        ),
    ]
