# Generated by Django 3.1.2 on 2021-01-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0016_auto_20210105_1059'),
        ('libmagapp', '0018_auto_20201101_2204'),
    ]

    operations = [
    ]
