# Generated by Django 3.1.2 on 2021-01-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0023_auto_20210107_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, default='book_cover', null=True, upload_to='book_cover', verbose_name='Bìa sách'),
        ),
    ]
