# Generated by Django 3.1.2 on 2021-01-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0027_auto_20210107_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/default_avatar.png', null=True, upload_to='user_avatar', verbose_name='Ảnh đại diện'),
        ),
    ]
