# Generated by Django 3.1.2 on 2021-01-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmagapp', '0028_auto_20210107_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Sẵn có'),
        ),
    ]
